# Generated by Django 5.1.7 on 2025-05-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('css_url', models.URLField(verbose_name='CSS URL')),
                ('js_url', models.URLField(blank=True, null=True, verbose_name='JS URL (optionnel)')),
                ('is_active', models.BooleanField(default=False, help_text='Définit si ce thème est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thème Admin',
                'verbose_name_plural': 'Thèmes Admin',
            },
        ),
    ]
