# Generated by Django 5.2.1 on 2025-05-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintheme',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Couleur de fond', max_length=7),
        ),
        migrations.AddField(
            model_name='admintheme',
            name='button_color',
            field=models.CharField(default='#2563eb', help_text='Couleur des boutons', max_length=7),
        ),
        migrations.AddField(
            model_name='admintheme',
            name='primary_color',
            field=models.CharField(default='#1d4ed8', help_text='Couleur principale (ex: boutons)', max_length=7),
        ),
        migrations.AddField(
            model_name='admintheme',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Couleur du texte', max_length=7),
        ),
    ]
