# Generated by Django 5.2.1 on 2025-05-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_theme', '0002_admintheme_background_color_admintheme_button_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintheme',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='admintheme',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='admintheme',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='admintheme',
            name='text_color',
        ),
    ]
