# Generated by Django 5.2.1 on 2025-05-23 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_theme', '0003_remove_admintheme_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintheme',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admintheme',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='admintheme',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='admintheme',
            name='scss_variables',
            field=models.TextField(blank=True, help_text='Variables SCSS personnalisées (format: variable: valeur;)'),
        ),
        migrations.AddField(
            model_name='admintheme',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='admintheme',
            name='sidebar_position',
            field=models.CharField(choices=[('left', 'Gauche'), ('right', 'Droite')], default='left', max_length=5),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='css_url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admintheme',
            name='js_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
